application: math-overflow
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: frontend/index.html
  upload: frontend/index.html
- url: /cache.manifest
  static_files: frontend/cache.manifest
  upload: frontend/cache.manifest
  mime_type: text/cache-manifest
- url: /
  static_dir: frontend
